### ISSUE TITLE
Depreciated packages

### ISSUE THREAD

**Issue by robsox** [sawirricardo/realworld-tall-app#2]
Hi, nice job on this real world app.
I noticed two installing stopping problems due to the lararavel 10 upgrade though.
Fideloper\TrustProxy and fruitcake\cors were integrated into Laravel as of version 9 so are causing an issue with composer compatibility.
I changed "use Fideloper\Proxy\TrustProxies as Middleware;" to "use Illuminate\Http\Middleware\TrustProxies as Middleware;" in TrustProxies.php and changed headers per https://github.com/fideloper/TrustedProxy/issues/152 then 
replaced "\Fruitcake\Cors\HandleCors::class," with "\Illuminate\Http\Middleware\HandleCors::class," in app/Http/Kernel.php per https://github.com/fruitcake/laravel-cors and everything worked perfectly. I would have done a pull request, but it seemed silly for such minor changes.
Thanks for your effort on this,
Rob

**Comment by sawirricardo** [comment]
Thanks, have fixed this @robsox
